replicaCount: 3
defaultReplicationFactor: 3
offsetsTopicReplicationFactor: 3
transactionStateLogReplicationFactor: 3
transactionStateLogMinIsr: 3

volumePermissions:
  enabled: true
zookeeper:
  volumePermissions:
    enabled: true
