apiVersion: v2
name: kafka-k8s-poc
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
  - name: kafka
    version: 7.2.6
    repository: https://charts.bitnami.com/bitnami
